PizzaStore.Client/Controllers/MovieController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using Microsoft.AspNetCore.Mvc;
using PizzaStore.Client.Models;
using PizzaStore.Domain.Models;
using PizzaStore.Storing;
using PizzaStore.Client.HttpClient;
using RestSharp;

namespace PizzaStore.Client.Controllers
{
  [Route("/movie/{id=1}")]
  // [Route("/store/")]
  // [EnableCors("private")]  
  public class MovieController : Controller
  {
    private readonly PizzaStoreDbContext _db;

    public MovieController(PizzaStoreDbContext dbContext) // constructor dependency injection
    {
      _db = dbContext;
    }

    [HttpGet]
    public IActionResult Get(int id)
    {
      var return_view = "index";

      switch (id)
      {
        case 1:           // display Search Movies by Title page 
          return_view = "ByTitle";
          return View(return_view, new MovieViewModel());
        case 2:          
          return View(return_view);
        case 3:          
          return View(return_view);
        case 4:          
          return View(return_view);
        default:
          return View(return_view);
      };

    }

    [HttpPost]
    public IActionResult Post(MovieViewIntModel movieViewModel, int id)
    {
      var return_view = "index";

      switch (id)
      {
        case 1:           // display Search Movie by Title results
          return_view = "ByTitle";
          break;
        case 2:
          break;
        default:
          break;
      }

      if (ModelState.IsValid) //  what is the validation? (add to viewmodel)
      {
        return_view = "MovieSearchResults";
        var searchString = movieViewModel.Title;
        // return View(return_view, GetMoviesByTitle(searchString));
        var movies = new GetMoviesClient();
        return View(return_view, movies.GetMoviesImdb("by_title", searchString));
        // return View(return_view, movies.GetMovies("imdb", "popular", null));
        // return View(return_view, movies.GetMovies("imdb", "trending", null));
        // return View(return_view, movies.GetMovies("imdb", "recently_added", null));
      }
      else
      {
        return View(return_view, movieViewModel);
      }

    }
  }
}

PizzaStore.Client/Controllers/OrderController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using PizzaStore.Client.Models;
using PizzaStore.Domain.Factories;
using PizzaStore.Domain.Models;
using PizzaStore.Storing;
using PizzaStore.Storing.Repository;

namespace PizzaStore.Client.Controllers
{
  [Route("/order/{id=1}")]
  // [EnableCors("private")]  
  public class OrderController : Controller
  {
    private readonly PizzaStoreDbContext _db;

    public OrderController(PizzaStoreDbContext dbContext) // constructor dependency injection
    {
      _db = dbContext;
    }

    [HttpGet]
    public IActionResult Get(int id)
    {
      var return_view = "";

      switch (id)
      {
        case 1:           // display available preset pizzas 
          return_view = "OrderStandard";
          break;
        case 2:           // display options for a custom pizza
          return_view = "OrderCustom";
          break;
        default:
          break;
      };
      return View(return_view, new PizzaViewModel());

    }

    [HttpPost]
    // [ValidateAntiForgeryToken]
    public IActionResult Post(PizzaViewModel pizzaViewModel, int id) //model binding
    {
      var return_view = "";
      switch (id)
      {
        case 1:           // set return view for standard pizza orders

          return_view = "OrderStandard";
          break;
        case 2:           // set return view for custom pizza orders
          pizzaViewModel.Type = "Custom";
          return_view = "OrderCustom";
          break;
        default:
          break;
      };

      if (ModelState.IsValid) //  what is the validation? (add to viewmodel)
      {
        var p = new PizzaFactory(); // use dependency injection
        PizzaModel domainPizzaModel = new PizzaModel();
        domainPizzaModel = p.Create();           // factory-created Domain PizzaModel

        if (pizzaViewModel.Types.Contains(pizzaViewModel.Type) || pizzaViewModel.Type == "Custom")
        {
          switch (id)
          {
            case 1:         //standard pizza chosen
              pizzaViewModel.SelectedToppings.Clear();
              pizzaViewModel.SelectedToppings.AddRange(pizzaViewModel.ToppingSets[pizzaViewModel.Type]);  // add topping sets based on chosen pizza type
              break;
            case 2:         //custom pizza chosen
              if (pizzaViewModel.SelectedToppings.Contains("dummy"))
                return View(return_view, pizzaViewModel);                   // no toppings were chosen at all, return to custom pizza order page  
              break;
            default:
              break;
          }

          var pricepertopping = 1.0m;
          switch (id)
          {
            case 1:           // set prices for standard pizza orders
              domainPizzaModel.Price = pizzaViewModel.Prices[pizzaViewModel.Type];
              break;
            case 2:           // set prices for custom pizza orders
              domainPizzaModel.Price = pizzaViewModel.Prices["Cheese"]; //cheapest
              domainPizzaModel.Price += pizzaViewModel.SelectedToppings.Count * pricepertopping;
              break;
            default:
              break;
          };
        }
        else
        {
          domainPizzaModel.Price = pizzaViewModel.Prices["Cheese"]; //cheapest
          pizzaViewModel.SelectedToppings.AddRange(pizzaViewModel.ToppingSets["Cheese"]);
        }

        // bind PizzaViewModel to Domain PizzaModel
        domainPizzaModel.Name = pizzaViewModel.Type;

        var newC = new CrustModel();
        newC.Name = pizzaViewModel.Crust;
        domainPizzaModel.Crust = newC;

        var newS = new SizeModel();
        newS.Name = pizzaViewModel.Size;
        domainPizzaModel.Size = newS;

        foreach (var t in pizzaViewModel.SelectedToppings)
        {
          var newToppings = new List<ToppingModel>();
          var newTopping = new ToppingModel();
          newTopping.Name = t;
          domainPizzaModel.Toppings.Add(newTopping);
        }

        var repo_pizza = new PizzaRepository();
        repo_pizza.Create(domainPizzaModel, _db);

        return_view = "ThankYou";
        return View(return_view);

      }


      return View(return_view, pizzaViewModel);
    }
  }
}

PizzaStore.Client/Controllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using Microsoft.AspNetCore.Cors;
using Microsoft.AspNetCore.Mvc;
using PizzaStore.Client.Models;
using PizzaStore.Domain.Factories;
using PizzaStore.Domain.Models;
using PizzaStore.Storing;
using PizzaStore.Storing.Repository;
using RestSharp;

namespace PizzaStore.Client.Controllers
{
  [Route("/store/{id=1}")]
  // [Route("/store/")]
  // [EnableCors("private")]  
  public class StoreController : Controller
  {
    private readonly PizzaStoreDbContext _db;

    public StoreController(PizzaStoreDbContext dbContext) // constructor dependency injection
    {
      _db = dbContext;
    }

    [HttpGet]
    public IActionResult Get(int id)
    {
      var return_view = "index";

      switch (id)
      {
        case 1:           // display Store Store Reports selection
          return View(return_view);
        case 2:          // display Store Sales History
          var storepizzalist = GetSales();
          return_view = "StoreSales";
          return View(return_view, storepizzalist);
        case 3:          // display Store Order History
          return View(return_view);
        case 4:          // display Search Movies by Title
          // GetMoviesByTitle();
          // return_view = "SearchByTitle";
          return View(return_view);
        default:
          return View(return_view);
      };
      

    }

    [HttpPost]
    public IActionResult Post(int id)
    {
      var return_view = "index";

      return View(return_view);  
    }

    public StoreViewModel GetSales()
    {
        var repo_pizza = new PizzaRepository();
        List<PizzaModel> pizzaList = repo_pizza.ReadAll(_db);
        StoreViewModel storepizzalist = new StoreViewModel();

        var price = 0.0m;
        var qty = 0;

        storepizzalist.Pizzas = pizzaList;
        storepizzalist.Toppings = new List<string>();
        foreach(var p in pizzaList.ToList())
        {
          List<string> toppings = new List<string>();
          foreach(var s in p.Toppings.ToList())
          {
            toppings.Add(s.Name);
          }
          storepizzalist.Toppings.Add(string.Join(",", toppings.ToArray()));

          price += p.Price;
          qty += 1;
        }

        storepizzalist.Qty = qty;
        storepizzalist.Price = price;
        
        return storepizzalist;
    }

    // public void GetMoviesByTitle()
    // {
    //   var client = new RestClient("https://movies-tvshows-data-imdb.p.rapidapi.com/?title=indiana%20jones&type=get-movies-by-title");
    //   var request = new RestRequest(Method.GET);
    //   request.AddHeader("x-rapidapi-host", "movies-tvshows-data-imdb.p.rapidapi.com");
    //   request.AddHeader("x-rapidapi-key", "971bf2ac6fmsh604c84512ded1eap16b86fjsn950b74fe77a7");
    //   IRestResponse response = client.Execute(request); 

    //   try
    //   {
    //     var movieList = JsonSerializer.Deserialize<MovieQByTitleModel>(response.Content);
    //   }
    //   catch (Exception e)
    //   {
    //     Console.WriteLine(e);
    //   }
      
    //   return;
    // }
  }
}

PizzaStore.Client/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PizzaStore.Client</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PizzaWorld</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="get" asp-route-id="1">Order a Standard Pizza</a>
                        </li>   
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="get" asp-route-id="2">Order a Custom Pizza</a>
                        </li>  
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Store" asp-action="get">Store</a>
                        </li>                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="get">Movies</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - PizzaWorld - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/jquery-validation/dist/jquery-validate.min.js"></script>
    <script src="~/lib/jquery-validation-unobstrusive/dist/jquery.validation.unobstrusive.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>